Modifying the startup script

diff --git a/templates/init-selendroid.erb b/templates/init-selendroid.erb
--- a/templates/init-selendroid.erb
+++ b/templates/init-selendroid.erb
@@ -1,8 +1,8 @@
 #! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          <%=@service_name%>
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Required-Start:    $local_fs $remote_fs $network
+# Required-Stop:     $local_fs $remote_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Start Selendroid server
@@ -10,16 +10,16 @@
 ### END INIT INFO
 
 # Author: Christopher Johnson <cjohn@ceh.ac.uk>
-
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Selendroid service wrapper"
 NAME=<%=@service_name%>
-JAVA_OPTS="-jar <%=@installed_path%>"
+DAEMON=<%=@wrapper_script%>
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
-
-# Run selendroid as this user ID
 SELENDROID_USER=<%=@user%>
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -41,11 +41,12 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE \
-		--user $SELENDROID_USER --exec "$JAVA_HOME/bin/java" --test > /dev/null \
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON \
+		--chuid $SELENDROID_USER --background --make-pidfile \
+		--test > /dev/null \
 		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE \
-		--user $SELENDROID_USER --exec "$JAVA_HOME/bin/java" -- $JAVA_OPTS \
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON  \
+		--chuid $SELENDROID_USER --background --make-pidfile \
 		|| return 2
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
@@ -62,8 +63,7 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE \
-					--user $SELENDROID_USER --name $NAME
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
 	# Wait for children to finish too if this is a daemon that forks
@@ -72,8 +72,7 @@ do_stop()
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 \
-					--user $SELENDROID_USER --exec "$JAVA_HOME/bin/java"
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --startas $DAEMON
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
 	rm -f $PIDFILE
@@ -89,8 +88,7 @@ do_reload() {
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
 	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE \
-					--user $SELENDROID_USER --name $NAME
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE
 	return 0
 }
 
@@ -112,8 +110,8 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc "$JAVA_HOME/bin/java" "$NAME" && exit 0 || exit $?
-       ;;
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
   #reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
@@ -140,7 +138,7 @@ case "$1" in
 		esac
 		;;
 	  *)
-	  	# Failed to stop
+		# Failed to stop
 		log_end_msg 1
 		;;
 	esac
